### ISSUE TITLE
train problem

### ISSUE THREAD

**Issue by zdj97** [fschmid56/EfficientAT#10]
when i run ex_audioset.py, there is a problem:

in line 111 :   x,f,y,i=batch

problem:  not enough values to unpack(expected4, got3)

I think the value i dose not have a value and I want to know how to use the teacher preds.

Thanks!

**Comment by fschmid56** [comment]
Hi! batch should be a tuple of 4 elements: the waveform (x), the filename (f), the label (y), and the index (i). The index is added as long as you don't call the function _get_full_training_set_ with _add_index=False_.

However, I have recently added a file _fname_to_index.pkl_ that contains a python dict for converting the filename to the respective index position in the numpy array that stores the predictions. As long as you have the latest version of the code in this repo, this new version should be used automatically.

**Comment by zdj97** [comment]
OK, Thanks! I will update the code.
