### ISSUE TITLE
Hack to get 1 dimensional output

### ISSUE THREAD

**Issue by turian** [fschmid56/EfficientAT#12]
I'm not sure why this was needed, but I had to add this hack to get num_classes=1 to work:

```
<             #num_classes = state_dict['classifier.1.bias'].size(0)
<             num_classes = state_dict['classifier.2.bias'].size(0)
---
>             num_classes = state_dict['classifier.1.bias'].size(0)
313,315d299
<             if "classifier.2.weight" in state_dict:
<                 del state_dict['classifier.2.weight']
<                 del state_dict['classifier.2.bias']
```

I won't push a fix because I don't understand the impact of this on other users. Perhaps it should only be used when num_classes is 1?

**Comment by fschmid56** [comment]
For which combination of parameters passed to the _get_model_ function does this happen?

Currently, if a pre-trained model is loaded via its name, e.g. _pretrained_name="mn10_as_fc"_ then the correct parameters have to be specified manually (e.g. _head_type="fully_convolutional"_). I will attach the correct config to the model names soon (after an upcoming deadline). This could be related to your problem.
