### ISSUE TITLE
Model input shape

### ISSUE THREAD

**Issue by cxmscb** [fschmid56/EfficientAT#16]
Thanks for the great work. I would like to ask the input(i.e.,x) shape of the mobilenet model, and is it (batch_size, 1, time_steps, mel_bins) or (batch_size, 1, mel_bins, time_steps)?

```
x = _mel_forward(x, mel)
y_hat, _ = model(x)
```

**Comment by fschmid56** [comment]
Thank you for your appreciation. 

The model's input is of shape: batch_size, 1, mel_bins, time_steps.

**Comment by cxmscb** [comment]
Thanks for the reply.
