### ISSUE TITLE
Question on use case

### ISSUE THREAD

**Issue by HeChengHui** [fschmid56/EfficientAT#31]
@fschmid56 
Thank you for your work! 
I am looking for ways to detect certain sounds among background noise. would like to check if this method can be used to finetune a model to detect a small number of sounds excluding background noise?

**Comment by fschmid56** [comment]
Hi @HeChengHui, sorry I was busy lately. 

To understand you correctly, you have sound files containing some events + background noise. You would like to ignore the background noise and detect the events, correct?

Do you have a dataset labeled with the events you would like to detect? In this case, you could just fine-tune one of the models of this repo on your dataset (as done e.g. in [ex_fsd50k.py](https://github.com/fschmid56/EfficientAT/blob/main/ex_fsd50k.py)).

You could also try to run the AudioSet pre-trained models without fine-tuning. Maybe the events you would like to detect are already present in the [AudioSet ontology](https://research.google.com/audioset/ontology/index.html) and the distribution shift between your audio clips and clips from AudioSet is not too severe.

Or is your goal to filter out the background noise?
