### ISSUE TITLE
ImageNet training results

### ISSUE THREAD

**Issue by hbellafkir** [fschmid56/EfficientAT#33]
Thank you for sharing your work. Could you also provide the evaluation results from the ImageNet training?

**Comment by fschmid56** [comment]
Hi! ImageNet pre-training was mostly done by a colleague of mine. However, I remember that we used [this repo](https://github.com/libffcv/ffcv-imagenet).

And I also found some old logs with some results:

MN10: 'top_1': 0.7186, 'top_5': 0.9076
DyMN10: 'top_1': 0.7320, 'top_5': 0.9119

However, these results might not exactly match the checkpoints uploaded to this repo. But the results should be somewhat similar if you need them for a sanity check.

**Comment by hbellafkir** [comment]
Thanks for the quick reply.
