### ISSUE TITLE
I want to use the dymn-L model, how can I use it?

### ISSUE THREAD

**Issue by chartgod** [fschmid56/EfficientAT#34]
I want to use the dymn-L model, how can I use it?

**Comment by fschmid56** [comment]
Hi @chartgod ! What do you want to use it for? A downstream task or inference?

**Comment by chartgod** [comment]
inference!
Is dymn20_as Dymn-L?

**Comment by fschmid56** [comment]
You should be able to simply use [this script](https://github.com/fschmid56/EfficientAT/blob/main/inference.py). An example command is listed in the readme file. 

You are correct, "dymn20_as" is DyMN-L from the paper.

Let me know if you encounter any problems.
