### ISSUE TITLE
multiple gpus support

### ISSUE THREAD

**Issue by didadida-r** [fschmid56/EfficientAT#4]
Hi, 

how to train the script using multiple gpus? thanks

**Comment by fschmid56** [comment]
Hi, this script is kept as simple as possible, also because most of the models can be trained in a single day on a consumer-grade GPU on AudioSet. For what purpose would you need multiple GPU support?

**Comment by didadida-r** [comment]
Well, I just think it would be more convenient to do some experiments if we support multi-gpu training

**Comment by fschmid56** [comment]
Okay, I'm currently busy with a deadline, so if you implement it and create a pull request that would be nice. Otherwise, I'll do it but it will take a bit.

**Comment by turian** [comment]
@didadida-r If you just use [pytorch-lightning](https://github.com/Lightning-AI/pytorch-lightning), you get multi GPU training on any `torch.nn.Module`. Seems like that would be a better and more generic solution for you

**Comment by fschmid56** [comment]
I added the [ex_pl_audioset.py](https://github.com/fschmid56/EfficientAT/blob/main/ex_pl_audioset.py) file for multi GPU training on AudioSet.
