### ISSUE TITLE
How to accurately identify the sound event offset?

### ISSUE THREAD

**Issue by joewale** [fschmid56/EfficientAT#5]
Hi，fschmid，I have a question: How to accurately identify the sound event offset?  As is known, the sound events in our life are endless, and some events are not the sound event categories in the Audioset. How to accurately identify these?

**Comment by fschmid56** [comment]
Hi Joewale,

> How to accurately identify the sound event offset?

I think what you are looking for is what we discussed [here](https://github.com/fschmid56/EfficientAT/issues/3). There will be more work from my side in this direction in the near future.

> As is known, the sound events in our life are endless, and some events are not the sound event categories in the Audioset. How to accurately identify these?

Do you have a small dataset for the new sound events? Then you have two options: use the models in this repo as embeddings extractors and train a shallow classifier on top of it (e.g. a simple one-layer MLP, see [here](https://github.com/fschmid56/EfficientAT_HEAR)  for examples how to get embeddings), or fine-tune the models in this repo such as done in [this file](https://github.com/fschmid56/EfficientAT/blob/main/ex_dcase20.py).

**Comment by joewale** [comment]
Thank you for you reply! 
Sorry, maybe my description is unclear. My question is how to avoid the audio of the 10s duration , which is not the sound event type in our label, being error recognized as the sound event label in our trainset.

**Comment by fschmid56** [comment]
I'm still not sure what you mean. Can you elaborate on what you mean by _sound event type in our label_ and _avoid the audio of 10s duration_? For the former, would you like to tag shorter audio clips?
