### ISSUE TITLE
error when train with "python ex_audioset.py --cuda --train"

### ISSUE THREAD

**Issue by mmuguang** [fschmid56/EfficientAT#9]
![image](https://user-images.githubusercontent.com/38957296/222153535-5c817e84-7667-4e61-b59e-8bcc0a240b97.png)

**Comment by fschmid56** [comment]
Hi! There could be two sources of problems:
- Check if the ID is in the official [csv files](https://research.google.com/audioset/download.html). The keys in the dict _fname_to_index__ correspond to the Youtube IDs. 
- I pushed a fix to a problem I'm aware of - AudioSet is downloaded from Youtube, so there could be a small portion of files I don't have in my version of the dataset.  The IDs of files I couldn't download successfully are not in the dict __fname_to_index__ and I can't provide teacher predictions for them. In the version I uploaded, if a file ID is not found in __fname_to_index__ the distillation loss is set to 0 for the corresponding sample.

**Comment by mmuguang** [comment]
Another question is that how u train the [mn40_as_no_im_pre_mAP_483.pt].
I use this command "python ex_audioset.py --cuda --train --model_width=4.0" ,but the mAP is around 0.42

**Comment by fschmid56** [comment]
The code base should be fine in general. I recently trained several models and it worked out as expected. I'll try to train a model with a width of 4.0 and tell you the exact command.

**Comment by fschmid56** [comment]
For me it looks like it works fine, e.g. you can follow the experiment using the command:

`python ex_audioset.py --cuda --train --model_width=4.0 --batch_size=60 --max_lr=0.0004`

Here is the [experiment on W&B](https://wandb.ai/florians/EfficientAudioTagging/reports/mn40-test-run--VmlldzozNzIwNzE0?accessToken=d95e670katc752zdni5mmy0t3muhcsdm7fkpxc7rbd7rcm7izyww0gewralqwqbb), currently running.
